export const fileNo: string = "सं0 एफ‐17013/1/PAO(D)/बजट/2024‐25/";
export const fileNoList : string[] = [
    "सं0 एफ‐17013/1/PAO(D)/बजट/2024‐25/",
    "सं0 एफ‐17013/2/RPAO(K)/बजट/2024‐25/",
    "सं0 एफ‐17013/3/RPAO(R)/बजट/2024‐25/",
    "सं0 एफ‐17013/4/RPAO(C)/बजट/2024‐25/",
    "सं0 एफ‐17013/5/RPAO(M)/बजट/2024‐25/",
]

export const reciverAddressList: any = [
    {
        value: [
            "वेतन एंव लेखा अधिकारी,",
            "वेतन एंव लेखा कार्यालय (के.औ.सु.ब.), गृह मन्त्रालय,",
            "5th Floor, E Block, GPO, INA, New Delhi.",
        ],
        label:
            "New Delhi"

    },
    {
        value: [
            "वेतन एंव लेखा अधिकारी,",
            "क्षेत्रीय वेतन एंव लेखा कार्यालय (के.औ.सु.ब.)",
            "गृह मन्त्रालय, Kolkata",
        ],
        label:
            "Kolkata"
    },
    {
        value: [
            "वेतन एंव लेखा अधिकारी,",
            "क्षेत्रीय वेतन एंव लेखा कार्यालय (के.औ.सु.ब.)",
            "गृह मन्त्रालय, Ranchi",
        ],
        label:
            "Ranchi"
    },
    {
        value: [
            "वेतन एंव लेखा अधिकारी,",
            "क्षेत्रीय वेतन एंव लेखा कार्यालय (के.औ.सु.ब.)",
            "गृह मन्त्रालय, Chennai",
        ],
        label:
            "Chennai"
    },
    {
        value: [
            "वेतन एंव लेखा अधिकारी,",
            "क्षेत्रीय वेतन एंव लेखा कार्यालय (के.औ.सु.ब.)",
            "गृह मन्त्रालय, Mumbai",
        ],
        label:
            "Mumbai"
    },
]

export const headCode: Object = {
    "SAL": "01.02.01",
    "WAGES": "01.02.02",
    "REW": "01.02.05",
    "MT": "01.02.06",
    "ALLOW": "01.02.07",
    "LTC": "01.02.08",
    "TRG EXP": "01.02.09",
    "DTE": "01.02.11",
    "FTE": "01.02.12",
    "OE": "01.02.13",
    "RRT for L & B": "01.02.14",
    "P & P": "01.02.16",
    "RENT FOR OTHERS": "01.02.18",
    "D E": "01.02.19",
    "M & S": "01.02.21",
    "M & S [MOD]": "01.01.21",
    "A & A": "03.00.75",
    "A & A [MOD]": "01.01.22",
    "COR": "01.02.23",
    "F & L": "01.02.24",
    "A & P": "01.02.26",
    "MC & EW": "01.02.27",
    "PS": "01.02.28",
    "R & M": "01.02.29",
    "GRANTS-IN-AID": "01.02.31",
    "SECRET SERVICE EXPENSES": "01.02.41",
    "ORE (CHARGED)": "01.02.49",
    "RECTT. (OE)": "01.03.13",
    "RECTT. (ADVT. & PUB)": "01.03.26",
    "CRECHE FACILITIES [ORE]": "01.04.49",
    "SDSP (ORE)": "01.05.49",
    "SAP (ORE)": "01.96.49",
    "MV": "03.00.51",
    "MV [MOD]": "04.00.51",
    "M & E": "03.00.52",
    "M & E [MOD]": "04.00.52",
    "ICTE": "03.00.71",
    "OB [B&S]": "01.00.72",
    "RB [B&S]": "02.00.72",
    "F & F": "03.00.74",
    "LAND": "03.00.78"
}



export const senderAddressList: string[] = [

    "13 के. स. का.परिसर",
    "लोधी रोड़ नई दिल्ली‐03",

]

export const data: any = [
    {
        key: 'Name of DDOs',
        value: []
    }
]

export const date: string = "दिनांक /02/2024";

export const ddoList: string[] = [
    "AO(Bill) CISF HQrs New Delhi",
    "ADG(North) CISF New Delhi",
    "ADG CISF APS HQrs New Delhi",
    "IG CISF NS HQrs New Delhi",
    "IG CISF NCR Sector New Delhi",
    "IG CISF DAE&DOS Sector New Delhi",
    "DIG CISF NZ HQrs New Delhi",
    "DIG CISF NZ-II HQrs Jammu",
    "DIG CISF NCR Zone HQrs New Delhi",
    "DIG CISF Unit DMRC New Delhi",
    "DIG CISF Unit CGBS New Delhi",
    "DIG CISF DOS Zone-II HQrs New Delhi",
    "DIG CISF AP-NZ HQrs New Delhi",
    "DIG CISF Unit IGI Airport New Delhi",
    "DIG CISF Unit SSG Greater Noida",
    "DIG CISF Unit CSI Airport Mumbai",
    "DIG CISF RTC Barwaha",
    "DIG CISF RTC-I Deoli",
    "DIG CISF MPRTC Behrore",
    "Gp. Comdt. CISF Gp HQrs New Delhi",
    "Gp. Comdt. CISF Gp HQrs Chandigarh",
    "Gp. Comdt. CISF Gp HQrs Mumbai",
    "Gp. Comdt. CISF Gp HQrs Ahmedabad",
    "Comdt. CISF 1st Res. Bn. Barwaha",
    "Comdt. CISF 5th Res. Bn. Ghaziabad",
    "Comdt. CISF 6th Res. Bn. Deoli",
    "Comdt. CISF 7th Res. Bn. Jaipur",
    "Comdt. CISF 8th Res. Bn. Deoli",
    "Comdt. CISF 9th Res. Bn. Deoli",
    "Comdt. CISF 11th Res. Bn. Greater Noida",
    "Comdt. CISF 12th Res. Bn. Behror",
    "Comdt.(Ord) CISF Ghaziabad",
    "Comdt. CISF Unit P&H Sectt. Chandigarh",
    "Comdt. CISF Unit SHEP Salal",
    "Comdt. CISF Unit DHEP Dulhasti",
    "Comdt. CISF Unit UHEP Uri",
    "Comdt. CISF Unit HTPP Kasimpur",
    "Comdt. CISF Unit BHEL Haridwar",
    "Comdt. CISF Unit PTPS Panki",
    "Comdt. CISF Unit KGHEP Bandipora",
    "Comdt. CISF Unit Taj Mahal Agra",
    "Comdt. CISF Unit NTPC Dadri",
    "Comdt. CISF Unit Red Fort New Delhi",
    "Comdt. CISF Unit DAMEPL Delhi",
    "Comdt. CISF Unit IOC Panipat",
    "Comdt. CISF Unit ONGC Mumbai",
    "Comdt. CISF Unit JNPA Sheva",
    "Comdt. CISF Unit ISP Nasik",
    "Comdt. CISF Unit ONGC Ahmedabad",
    "Comdt. CISF Unit ONGC Ankleshwar",
    "Comdt. CISF Unit DPA Kandla",
    "Comdt. CISF Unit RCFL Mumbai",
    "Comdt. CISF Unit HPCL/BPCL Mumbai",
    "Comdt. CISF Unit MPA Goa",
    "Comdt. CISF Unit MbPA Mumbai",
    "Comdt. CISF Unit TAPS Tarapur",
    "Comdt. CISF Unit NAPS Narora",
    "Comdt. CISF Unit RAPS Kota",
    "Comdt. CISF Unit KAPS Kakarpara",
    "Comdt. CISF Unit SAC Ahmedabad",
    "Comdt. CISF Unit BHEL Bhopal",
    "Comdt. CISF Unit Airport Amritsar",
    "Comdt. CISF Unit Airport Lucknow",
    "Comdt. CISF Unit Airport Srinagar",
    "Comdt. CISF Unit Airport Jammu",
    "Comdt. CISF Unit Airport Chandigarh",
    "Comdt. CISF Unit Airport Varanasi",
    "Comdt. CISF Unit Airport Jaipur",
    "Comdt. CISF Unit SVPIA Ahmedabad",
    "Comdt. CISF Unit Airport Goa",
    "Comdt. CISF Unit IOC GR Baroda",
    "Comdt. CISF Unit Airport Pune",
    "Comdt. CISF Unit MOPA Goa Airport",
    "DC CISF Unit NFL Nangal",
    "DC CISF Unit BSHEPP Surangani",
    "DC CISF Unit CPS-I Khairi",
    "DC CISF Unit NFL Bathinda",
    "DC CISF Unit THDC Tehri",
    "DC CISF Unit PTPP Parichha",
    "DC CISF Unit AUGPP/NTPC Dibiyapur",
    "DC CISF Unit GAIL Pata",
    "DC CISF Unit KTPS Kota",
    "DC CISF Unit CHEP Chamera-II",
    "DC CISF Unit SJVNL Jhakri",
    "DC CISF Unit NTPC Koldam",
    "DC CISF Unit SSTPS Surathgarh",
    "DC CISF Unit NLC Barsingsar",
    "DC CISF Unit RGTPP Khedar",
    "DC CISF Unit IGSTPP Jhaarli Jhajjar",
    "DC CISF Unit UHEP URI-II",
    "DC CISF Unit UIDAI Manesar",
    "DC CISF Unit GTPS Ghatampur",
    "DC CISF Unit SSCTPP Suratgarh",
    "DC CISF Unit IOC Mathura",
    "DC CISF Unit FGUTPP Unchahar",
    "DC CISF Unit NM New Delhi",
    "DC CISF Unit NFL Panipat",
    "DC CISF Unit PTPS Panipat",
    "DC CISF Unit IPGCL/PPCL Delhi",
    "DC CISF Unit PPCL-III Bawana",
    "DC CISF Unit CNP Nasik",
    "DC CISF Unit ONGC Mehsana",
    "DC CISF Unit UTPS Ukai",
    "DC CISF Unit KGPP Kawas",
    "DC CISF Unit SMPL Vadinar",
    "DC CISF Unit ONGC Hazira",
    "DC CISF Unit JGGPP Jhanoor",
    "DC CISF Unit GSL Goa",
    "DC CISF Unit MSTPP Mouda",
    "DC CISF Unit Statue of Unity Ekta Nagar",
    "DC CISF Unit NFL Vijaipur",
    "DC CISF Unit GAIL Vijaipur",
    "DC CISF Unit DHEP Dhauliganga",
    "DC CISF Unit PGCIL New Wanpoh",
    "DC CISF Unit Samadhi Sthal Delhi",
    "DC CISF Unit VPHEP Pipalkoti",
    "DC CISF Unit Airport Udaipur",
    "DC CISF Unit Airport Jodhpur",
    "DC CISF Unit Airport Dehradun",
    "DC CISF Unit Airport Leh Ladakh",
    "DC CISF Unit Airport Nagpur",
    "DC CISF Unit Airport Vadodara",
    "DC CISF Unit Airport Rajkot",
    "DC CISF Unit Airport Bhopal",
    "DC CISF Unit Airport Indore",
    "DC CISF Unit Airport Aurangabad",
    "DC CISF Unit Airport Shirdi",
    "DC CISF Unit Airport Surat",
    "AC CISF Unit Airport Porbandar",
    "AC CISF Unit Airport Shimla",
    "AC CISF Unit Airport Agra",
    "AC CISF Unit IIRS Dehradun",
    "IG CISF NES-II HQrs Kolkata",
    "IG CISF NES HQrs Guwahati",
    "IG CISF CS HQrs Bhilai",
    "DIG CISF NEZ-II HQrs Kolkata",
    "DIG CISF Unit DSP Durgapur",
    "DIG CISF Unit ISP Burnpur",
    "DIG CISF NEZ HQrs Guwahati",
    "DIG CISF Unit BSP Bhilai",
    "DIG CISF Unit SECL Bilaspur",
    "DIG CISF CZ HQrs Bhilai",
    "DIG CISF AP-E&NE HQrs Kolkata",
    "DIG CISF Unit NSCBIA Kolkata",
    "DIG CISF RTC Bhilai",
    "Gp. Comdt. CISF Gp HQrs Kolkata",
    "Gp. Comdt. CISF Gp HQrs Guwahati",
    "Comdt CISF Unit ONGC Nazira",
    "Comdt. CISF 3rd Res. Bn. Bhilai",
    "Comdt. CISF Unit KoPT Kolkata",
    "Comdt. CISF Unit DTPS Durgapur",
    "Comdt. CISF Unit ECL Seetalpur",
    "Comdt. CISF Unit HDC Haldia",
    "Comdt. CISF Unit FBP Farakka",
    "Comdt. CISF Unit FSTPP Farakka",
    "Comdt. CISF Unit GRSEL Kolkata",
    "Comdt. CISF Unit MTPS Mejia",
    "Comdt. CISF Unit BRBNML Salboni",
    "Comdt. CISF Unit ONGC Jorhat",
    "Comdt. CISF Unit BRPL Bongaigaon",
    "Comdt. CISF Unit OIL Duliajan",
    "Comdt. CISF Unit BTPP/NTPC Salakati",
    "Comdt. CISF Unit KSTPP Korba",
    "Comdt. CISF Unit BIOP DEP-5 Bacheli",
    "Comdt. CISF Unit BNP Dewas",
    "Comdt. CISF Unit SPM Narmdapuram",
    "Comdt. CISF Unit BIOM Kirandul",
    "Comdt. CISF Unit WCL Chindwara",
    "Comdt. CISF Unit Airport Guwahati",
    "Comdt. CISF Unit NRL Numaligarh",
    "Comdt. CISF Unit NISP Nagarnar",
    "DC CISF Unit RTPP Purulia",
    "DC CISF Unit DSTPS Andal",
    "DC CISF Unit VMH Kolkata",
    "DC CISF Unit IOC Haldia",
    "DC CISF Unit Port Blair Port",
    "DC CISF Unit IOC Guwahati",
    "DC CISF Unit BVFCL Namrup",
    "DC CISF Unit NHPCL/SLP Gurukamukh",
    "DC CISF Unit BCPL Dibrugarh",
    "DC CISF Unit NSPCL Bhilai",
    "DC CISF Unit KSTPP/NTPC Khargone",
    "DC CISF Unit RRCAT Indore",
    "DC CISF Unit IOCL Digboi",
    "DC CISF Unit GSTPP Gadarwara",
    "DC CISF Unit LSTPP Raigarh",
    "DC CISF Unit Airport Bagdogra",
    "DC CISF Unit Airport Dibrugarh",
    "DC CISF Unit Airport Agartala",
    "DC CISF Unit Airport Raipur",
    "DC CISF Unit Airport Dimapur",
    "DC CISF Unit Airport Imphal",
    "DC CISF Unit Airport Port Blair",
    "DC CISF Base Work Shop Bhilai",
    "AC CISF Unit NTPC Sipat",
    "AC CISF Unit DHEP Doyang",
    "AC CISF Unit ISTRAC Portblair",
    "AC CISF Unit Airport Lilabari",
    "AC CISF Unit Airport Silchar",
    "AC CISF Unit Airport Tezpur",
    "AC CISF Unit Airport Shillong",
    "AC CISF Unit Airport Jorhat",
    "IG CISF ES HQrs Ranchi",
    "DIG CISF EZ HQrs Patna",
    "DIG CISF EZ-II HQrs Allahabad",
    "DIG CISF Unit BCCL-CCWO Dhanbad",
    "DIG CISF Unit BSL Bokaro",
    "DIG CISF Unit CCL Ranchi",
    "DIG CISF NEZ-III HQrs Mundali",
    "DIG CISF Unit RSP Rourkela",
    "DIG CISF RTC Mundali",
    "Gp. Comdt. CISF Gp HQrs Patna",
    "Gp. Comdt. CISF Gp HQrs Allahabad",
    "Comdt. CISF 2nd Res. Bn. Ranchi",
    "Comdt. CISF Unit PTPS Patratu",
    "Comdt. CISF Unit IOC Barauni",
    "Comdt. CISF Unit KHSTPP Kahalgaon",
    "Comdt. CISF Unit PPA Paradip",
    "Comdt. CISF Unit NALCO Angul",
    "Comdt. CISF Unit NALCO Damanjodi",
    "Comdt./Mines CISF Unit BOM Bolani",
    "Comdt. CISF Unit IOCL Paradip",
    "Comdt. CISF Unit UCIL Jaduguda",
    "Comdt. CISF Unit SSTPS Shaktinagar",
    "Comdt. CISF Unit OTHPP Obra",
    "Comdt. CISF Unit ATPP Anpara",
    "Comdt. CISF Unit VSTPS Vindhyanagar",
    "Comdt. CISF Unit NCL Singrauli",
    "Comdt. CISF Unit Airport Patna",
    "Comdt. CISF Unit Airport Bhuwaneswar",
    "DC CISF Unit TTPS Lalpania",
    "DC CISF Unit KBUNL Kanti",
    "DC CISF Unit NTPC Barh",
    "DC CISF Unit KTPP Kodarma",
    "DC CISF Unit NPGCL Nabinagar",
    "DC CISF Unit BTPS Barauni",
    "DC CISF Unit HEC Ranchi",
    "DC CISF Unit CTPS Chandrapura",
    "DC CISF Unit BTPS DVC Bokaro",
    "DC CISF Unit DVC Maithon",
    "DC CISF Unit MBR-KBR Meghahatuburu",
    "DC CISF Unit NTPC Kaniha",
    "DC CISF Unit NTPC/TTPS Talcher",
    "DC CISF Unit BOM Bolani",
    "DC CISF Unit GUA ORE Mines",
    "DC CISF Unit TSL Kalinganagar",
    "DC CISF Unit RHPP Pipri",
    "DC CISF Unit NTPC/TTPP Tanda",
    "DC CISF Unit RhSTPP Rihandnagar",
    "DC CISF Unit BRBCL Nabinagar",
    "DC CISF Unit Airport Gaya",
    "DC CISF Unit Airport Ranchi",
    "IG CISF SS HQrs Chennai",
    "IG CISF NISA Hyderabad",
    "IG CISF APS-II HQrs Bangalore",
    "DIG CISF SZ-I HQrs Chennai",
    "DIG CISF SZ-II HQrs Hyderabad",
    "DIG CISF Unit NLC Nayveli",
    "DIG CISF RTC Arakkonam",
    "DIG CISF DOS HQrs Bangalore",
    "DIG CISF DAE HQrs Hyderabad",
    "DIG CISF AP-SZ HQrs Chennai",
    "DIG CISF Unit Airport Chennai",
    "DIG CISF Unit Airport Hyderabad",
    "DIG CISF Unit Airport Bangalore",
    "DIG CISF FSTI Hyderabad",
    "Gp. Comdt. CISF Gp HQrs Chennai",
    "Gp. Comdt. CISF Gp HQrs Cochin",
    "Gp. Comdt. CISF Gp HQrs Hyderabad",
    "Comdt. CISF 4th Res. Bn. Sivgangai",
    "Comdt. CISF 10th Res. Bn. Arakkonam",
    "Comdt. CISF Unit VPA Vishakhapatnam",
    "Comdt. CISF Unit ChPA Chennai",
    "Comdt. CISF Unit FACT Udyogmandal",
    "Comdt. CISF Unit BHEL Hyderabad",
    "Comdt. CISF Unit BDL Kanchanbagh",
    "Comdt. CISF Unit SCCL Singareni",
    "Comdt. CISF Unit RSTPS Ramagundam",
    "Comdt. CISF Unit VSP Vishakhapatnam",
    "Comdt. CISF Unit RTPS Raichur",
    "Comdt. CISF Unit DAE Kalpakkam",
    "Comdt. CISF Unit VSSC Thumba",
    "Comdt. CISF Unit SDSC SHAR Sriharikota",
    "Comdt. CISF Unit NFC Hyderabad",
    "Comdt. CISF Unit URSC Bangalore",
    "Comdt. CISF Unit HWP Manuguru",
    "Comdt. CISF Unit NPC Kaiga",
    "Comdt. CISF Unit KKNPP Kundakulam",
    "Comdt. CISF Unit Airport Cochin",
    "Comdt. CISF Unit Airport Trivandrum",
    "Comdt. CISF Unit Airport Kannur",
    "Comdt. CISF Unit Airport Mangalore",
    "Comdt. CISF Unit Airport Coimbatore",
    "Comdt. CISF Unit Airport Calicut",
    "DC CISF Unit SSP Salem",
    "DC CISF Unit CPCL Manali",
    "DC CISF Unit NMPA Mangalore",
    "DC CISF Unit CSY Cochin",
    "DC CISF Unit IG MINT Hyderabad",
    "DC CISF Unit HPCL Vishakhapatnam",
    "DC CISF Unit BRBNMPL Mysore",
    "DC CISF Unit STPP Simadhri",
    "DC CISF Unit BPCL Kochi Refinery",
    "DC CISF Unit SVP/NPA Hyderabad",
    "DC CISF Unit MRPL Mangalore",
    "DC CISF Unit VTPP Vallur",
    "DC CISF Unit VOCPA Tuticorin",
    "DC CISF Unit CPA Cochin",
    "DC CISF Unit MCF Hassan",
    "DC CISF Unit NRSC Balanagar",
    "DC CISF Unit LPSC Mahendragiri",
    "DC CISF Unit LPSC Valiamala",
    "DC CISF Unit Infosys Tech Ltd. Bangalore",
    "DC CISF Unit KPL Ennore",
    "DC CISF Unit DIOM Donimalai",
    "DC CISF Unit Airport Trichy",
    "DC CISF Unit Airport Madurai",
    "DC CISF Unit Airport Vizag",
    "DC CISF Unit Airport Tirupati",
    "DC CISF Unit UIDAI Bengaluru",
    "ADG(South) CISF Navi Mumbai",
    "IG CISF WS HQrs Mumbai",
    "DIG CISF WZ HQrs Mumbai",
    "DIG CISF DAE Zone-II HQrs Mumbai",
    "DIG CISF AP-WZ HQrs Mumbai",
    "Comdt. CISF Unit BARC Mumbai",
    "DC CISF Unit MDL Mumbai",
    "DC CISF Unit RCFL Thal",
    "DC CISF Unit CSTPS Chandrapur",
    "DC CISF Unit RCP Navi Mumbai",
    "DC CISF Unit JIO World Centre Mumbai",
]
